Repository paketo-buildpacks/java-native-image, pull requests merged in 2020-11, with the labels that each got.

#22 Update Pipelines Workflow
  .github/pipeline-descriptor.yml
  .github/workflows/update-pipeline.yml
Labels: semver:patch, type:task

#24 CA Certificates
  README.md
  buildpack.toml
  package.toml
Labels: semver:major, type:enhancement

#27 ca-certificates Update Workflow
  .github/workflows/update-ca-certificates.yml
Labels: semver:patch, type:task

#29 GitHub Token
  .github/pipeline-descriptor.yml
  .github/workflows/update-pipeline.yml
Labels: semver:patch, type:task

#31 Registry Uses Main Token
  .github/pipeline-descriptor.yml
Labels: semver:patch, type:task

#34 Remove Paketo CA Certficates buildpack
  .github/workflows/update-ca-certificates.yml
  README.md
  buildpack.toml
  package.toml
Labels: semver:patch, type:bug

#47 Docker URI
  package.toml
Labels: semver:patch, type:task
